import type { Metadata, Viewport } from "next";

import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

import BootstrapClient from "@/components/BootstrapClient";
import { ToastProvider } from "@/context/ToastContext";

export const metadata: Metadata = {
  title: "MabsolCrm",
  description: "Generated by Mabsol Infotech",
  other: {
    "color-scheme": "light",
  },
  icons: {
    icon: "/mabsol_logo.ico",
    shortcut: "/mabsol_logo.ico",
    apple: "/mabsol_logo.ico",
  },
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{ colorScheme: "light" }}>
      <body className="min-h-screen bg-[#f8fafc] text-slate-900" style={{ colorScheme: "light" }}>
        <ToastProvider>
          <BootstrapClient />
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}